version: "2"

volumes:
  mysql:
  project:
  results:

services:
  mysql:
    image: boinc/server_mysql
    network_mode: bridge
    volumes:
     - "mysql:/var/lib/mysql"
    environment: 
     - MYSQL_ROOT_PASSWORD=
     - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  makeproject:
    build: 
      context: .
      args: 
        GITTAG: 
    network_mode: bridge
    links: 
     - mysql
    volumes:
     - "project:/root/project.dst"

  apache:
    build: apache
    network_mode: bridge
    hostname: ProjectStreet
    links:
     - mysql
    volumes: 
     - "project:/root/project"
     - "results:/results"
     - "/var/run/docker.sock:/var/run/docker.sock"
     - "./letsencrypt:/etc/letsencrypt"
    ports: 
     - "80:80"
     - "443:443"
    tty: true


#---------
# backups
#---------

  mysql-backup:
    image: debian:jessie
    volumes:
      - "mysql:/var/lib/mysql"
      - "./backups:/backups"
    command:
      [sh,-c,"tar cvf /backups/mysql_$$(date -I).tar /var/lib/mysql"]

  project-backup:
    image: debian:jessie
    volumes:
      - "project:/project"
      - "./backups:/backups"
    command:
      [sh,-c,'tar cvf /backups/project_$$(date -I).tar /project --exclude="*log*"']
