version: "2"

volumes:
  mysql:
  mysql_vmail:
  project:
  results:
  vmail:
  log:

services:
  mysql:
    image: boinc/server_mysql
    network_mode: bridge
    volumes:
     - "mysql:/var/lib/mysql"
    environment: 
     - MYSQL_ROOT_PASSWORD=
     - MYSQL_ALLOW_EMPTY_PASSWORD=yes
     
  mysql_vmail:
    image: mysql
    network_mode: bridge
    volumes:
     - "mysql_vmail:/var/lib/mysql"
    environment: 
     - MYSQL_ROOT_PASSWORD=vmail

  makeproject:
    build: 
      context: . 
      args:
        - GITTAG
    network_mode: bridge
    links: 
     - mysql
    volumes:
     - "project:/root/project.dst"

  apache:
    build: apache
    network_mode: bridge
    hostname: ProjectStreet
    links:
     - mysql
    volumes: 
     - "project:/root/project"
     - "results:/results"
     - "/var/run/docker.sock:/var/run/docker.sock"
     - "./letsencrypt:/etc/letsencrypt"
    ports: 
     - "8081:8081"
    tty: true
    environment:
     - VIRTUAL_HOST=projectstreet.dynu.com
     - VIRTUAL_PORT=8081
     
  mailserver:
    image: muellermh/mailserver
    network_mode: bridge
    hostname: mail
    links:
     - mysql_vmail
    volumes: 
     - "vmail:/var/vmail"
     - "log:/var/log"
    ports: 
     - "25:25"
     - "587:587"
     - "110:110"
     - "143:143"
     - "995:995"
     - "993:993"
    tty: true
    environment:
     - DB_HOST=mysql_vmail
     - DB_USER=root
     - DB_PASS=vmail
     - DB_NAME=vmail
     - HOST_MAIL=info@nordgedanken.de Nordgedanken Info
     - HOST_NAME=projectstreet.dynu.com

#---------
# backups
#---------

  mysql-backup:
    image: debian:jessie
    volumes:
      - "mysql:/var/lib/mysql"
      - "./backups:/backups"
    command:
      [sh,-c,"tar cvf /backups/mysql_$$(date -I).tar /var/lib/mysql"]

  project-backup:
    image: debian:jessie
    volumes:
      - "project:/project"
      - "./backups:/backups"
    command:
      [sh,-c,'tar cvf /backups/project_$$(date -I).tar /project --exclude="*log*"']
