version: "2"

volumes:
  mysql:
  project:
  results:
  vmail:
  log:

services:
  mysql:
    image: boinc/server_mysql
    network_mode: bridge
    volumes:
     - "mysql:/var/lib/mysql"
    environment: 
     - MYSQL_ROOT_PASSWORD=
     - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  makeproject:
    build: 
      context: . 
      args:
        - GITTAG
    network_mode: bridge
    links: 
     - mysql
    volumes:
     - "project:/root/project.dst"

  apache:
    build: apache
    network_mode: bridge
    hostname: ProjectStreet
    links:
     - mysql
    volumes: 
     - "project:/root/project"
     - "results:/results"
     - "/var/run/docker.sock:/var/run/docker.sock"
     - "./letsencrypt:/etc/letsencrypt"
    ports: 
     - "80:80"
     - "443:443"
    tty: true
    
  mailserver:
    image: muellermh/mailserver
    network_mode: bridge
    hostname: mail
    links:
     - mysql
    volumes: 
     - "vmail:/var/vmail"
     - "log:/var/log"
    ports: 
     - "25:25"
     - "587:587"
     - "110:110"
     - "143:143"
     - "995:995"
     - "993:993"
    tty: true
    environment:
     - DB_HOST=mysql
     - DB_USER=root
     - DB_PASS=
     - DB_NAME=vmail
     - HOST_MAIL=info@nordgedanken.de Nordgedanken Info

#---------
# backups
#---------

  mysql-backup:
    image: debian:jessie
    volumes:
      - "mysql:/var/lib/mysql"
      - "./backups:/backups"
    command:
      [sh,-c,"tar cvf /backups/mysql_$$(date -I).tar /var/lib/mysql"]

  project-backup:
    image: debian:jessie
    volumes:
      - "project:/project"
      - "./backups:/backups"
    command:
      [sh,-c,'tar cvf /backups/project_$$(date -I).tar /project --exclude="*log*"']
